---
title: "The correlated $N(0, 1)$ figure in `cashr`"
author: "Lei Sun"
date: "2018-10-03"
output:
  workflowr::wflow_html:
    code_folding: hide
---

## Introduction

Document the correlated $N(0, 1)$ figure in the `cashr` paper.

```{r}
source("../code/gdash_lik.R")
source("../code/gdfit.R")
source("../code/count_to_summary.R")
```

```{r}
#z.mat <- readRDS("../output/z_null_liver_777.rds")
#Z.gtex <- readRDS("../output/paper/simulation/Z.gtex.rds")
#sel = c(32, 327, 23, 459)
#z.sel <- z.mat[sel, ]
#z.sel[3, ] <- Z.gtex[[4503]]
z.sel <- readRDS("../output/paper/simulation/z.sel.rds")
```

```{r}
gd.ord <- 10

x.plot = seq(- max(abs(z.sel)) - 2, max(abs(z.sel)) + 2, length = 1000)
hermite = Hermite(gd.ord)
gd0.std = dnorm(x.plot)
matrix_lik_plot = cbind(gd0.std)
for (j in 1 : gd.ord) {
  gd.std = (-1)^j * hermite[[j]](x.plot) * gd0.std / sqrt(factorial(j))
  matrix_lik_plot = cbind(matrix_lik_plot, gd.std)
}

z = z.sel[4, ]
w <- gdfit(z, gd.ord, w.lambda = 10, w.rho = 0.5)$w
y.plot = matrix_lik_plot %*% w
z.hist = hist(z, breaks = 100, plot = FALSE)
y.max = max(z.hist$density, y.plot, dnorm(0))
```

```{r}
setEPS()
postscript("../output/paper/cor_z_hist.eps", width = 8, height = 6)
#pdf("../output/paper/cor_z_hist.pdf", width = 8, height = 6)

par(mfrow = c(2, 2)) # 2-by-2 grid of plots
par(oma = c(0.5, 2.5, 0, 0)) # make room (i.e. the 4's) for the overall x and y axis titles
par(mar = c(2, 2, 3.5, 1)) # make the plots be closer together

# now plot the graphs with the appropriate axes removed (via xaxt and yaxt),
# remove axis labels (so that they are not redundant with overall labels,
# and set some other nice choices for graphics parameters
for (i in 1 : 4) {
  z = z.sel[i, ]
  w <- gdfit(z, gd.ord)$w
  y.plot = matrix_lik_plot %*% w
  z.hist = hist(z, breaks = 100, plot = FALSE)
  hist(z, breaks = seq(-10, 10, by = 0.1), prob = TRUE, ylim = c(0, y.max), main = NULL, xlab = "", xlim = range(c(abs(z.sel), -abs(z.sel))))
  lines(x.plot, dnorm(x.plot), col = "blue", lwd = 2)
  lines(x.plot, y.plot, col = scales::hue_pal()(5)[5], lwd = 2)
  legend("topleft", bty = "n", paste0('(', letters[i], ')'), cex = 1.25)
}

# print the overall labels
mtext('Density', side = 2, outer = TRUE, line = 1)
mtext(latex2exp::TeX('Histograms of $10^4$ Correlated N(0,1) z-scores'), line = -2, outer = TRUE)

legend("topleft", inset = c(-0.65, -0.25), legend = c("N(0, 1)", "Gaussian Derivatives"), lty = 1, lwd = 2, xpd = NA, col = c("blue", scales::hue_pal()(5)[5]), ncol = 2)

dev.off()
```

## `ashr::plot_diagnostic` on these correlated noise

```{r, cache = TRUE, message = FALSE, warning = FALSE}
# for (i in 1 : 4) {
#   par(mfrow = c(1, 1))
#   z = z.sel[i, ]
#   hist(z, breaks = 100, prob = TRUE, ylim = c(0, y.max), main = NULL, xlab = "", xlim = range(c(abs(z.sel), -abs(z.sel))))
#   lines(x.plot, dnorm(x.plot), col = "green", lwd = 2)
#   par(mfrow = c(2, 2))
#   fit.ash.n <- ashr::ash(z, 1, mixcompdist = "normal", method = "fdr")
#   cat("mixcompdist = normal")
#   ashr::plot_diagnostic(fit.ash.n, breaks = 100, plot.hist = TRUE)
#   par(mfrow = c(2, 2))
#   fit.ash.u <- ashr::ash(z, 1, mixcompdist = "uniform", method = "fdr")
#   cat("mixcompdist = uniform")
#   ashr::plot_diagnostic(fit.ash.u, breaks = 100, plot.hist = TRUE)
#   par(mfrow = c(2, 2))
#   fit.ash.hu <- ashr::ash(z, 1, mixcompdist = "halfuniform", method = "fdr")
#   cat("mixcompdist = halfuniform")
#   ashr::plot_diagnostic(fit.ash.hu, breaks = 100, plot.hist = TRUE)
# }
```

## different methods applied to (c)

```{r}
## Multiple testing
q <- 0.1
z <- z.sel[3, ]
p <- pnorm(-abs(z)) * 2
## under 0.005
sum(p <= 0.005)
pnorm(qnorm(0.0025), 0, 1.6) * 2 * 1e4
p.bh <- p.adjust(p, method = "BH")
## BHq at FDR 0.05
sum(p.bh <= q)
fit.q <- qvalue::qvalue(p)
## pi0 by qvalue
fit.q$pi0
## qvalue at FDR 0.05
sum(fit.q$qvalues <= q)
## pi0 by ashr
fit.a <- ashr::ash(z, 1, mixcompdist = "normal", method = "fdr")
ashr::get_pi0(fit.a)
## ashr at FDR 0.05
sum(ashr::get_qvalue(fit.a) <= q)
```

## shoulder inflation figure

```{r}
## the image is 7.5 * 3
setEPS()
postscript("../output/paper/cor_z_cdf.eps", width = 8, height = 2.5)
#pdf("../output/paper/cor_z_cdf.pdf", width = 8, height = 2.5)

par(mfrow = c(1, 3))
par(oma = c(1, 2.5, 0, 8)) # make room (i.e. the 4's) for the overall x and y axis titles
par(mar = c(2, 2, 2.5, 1)) # make the plots be closer together

plot(ecdf(z), xlab = "", ylab = "", lwd = 2, main = expression("Figure 1(c) z-scores"), cex.main = 1.5)
lines(seq(-6, 6, by = 0.01), pnorm(seq(-6, 6, by = 0.01)), col = "blue", lwd = 2)
lines(seq(-6, 6, by = 0.01), pnorm(seq(-6, 6, by = 0.01), 0, 1.6), col = "green", lwd = 2)
rect(xleft = c(-5, 2.5),
     xright = c(-2.5, 5),
     ytop = c(0.05, 1),
     ybottom = c(0, 0.95), border = "red", lty = c(1, 5))

plot(ecdf(z), xlab = "", ylab = "", main = expression("left tail"), lwd = 2, xlim = c(-5, -2.5), ylim = c(0, 0.05), cex.main = 1.5, bty = "n")
box(col = "red")
lines(seq(-6, 6, by = 0.01), pnorm(seq(-6, 6, by = 0.01)), col = "blue", lwd = 2)
lines(seq(-6, 6, by = 0.01), pnorm(seq(-6, 6, by = 0.01), 0, 1.6), col = "green", lwd = 2)

plot(ecdf(z), xlab = "", ylab = "", main = expression("right tail"), lwd = 2, xlim = c(2.5, 5), ylim = c(0.95, 1), cex.main = 1.5, bty = "n")
box(col = "red", lty = 5)
lines(seq(-6, 6, by = 0.01), pnorm(seq(-6, 6, by = 0.01)), col = "blue", lwd = 2)
lines(seq(-6, 6, by = 0.01), pnorm(seq(-6, 6, by = 0.01), 0, 1.6), col = "green", lwd = 2)

mtext('CDF', side = 2, outer = TRUE, line = 1)

legend("topright", inset = c(-0.68, 0.3), legend = c('Figure 1(c)\nz-scores', 'N(0, 1)', expression(N(0, 1.6^2))), lty = 1, lwd = 2, xpd = NA, col = c('black', "blue", "green"), ncol = 1, cex = 1.25, bty = 'n')

dev.off()
```


```{r}
# 7.5 * 3
setEPS()
postscript("../output/paper/cor_z_pval.eps", width = 12, height = 3)
#pdf("../output/paper/cor_z_pval.pdf", width = 12, height = 3)

thresh.color <- c("maroon", "purple", "orange")
#thresh.color <- scales::hue_pal()(10)[5 : 7]

par(mfrow = c(1, 4))
par(oma = c(0, 0, 0, 11)) # make room (i.e. the 4's) for the overall x and y axis titles

par(mar = c(4.5, 4, 4.5, 1)) # make the plots be closer together
p.hist <- hist(p, breaks = seq(0, 1, by = 0.01), plot = FALSE)
plot(0, 0, xlab = "p-values", ylab = "", type = "n", xlim = c(0, 1), ylim = c(0, max(p.hist$density)), main = expression(atop("Histogram of p-val of", 'Figure 1(c) z-scores')), cex.main = 1.5, cex.lab = 1.5)
title(ylab = "Density", line = 2.5, cex.lab = 1.5)
abline(v = c(0.05 / 1e4, pnorm(-sqrt(2 * log(1e4))) * 2, 0.005), lwd = 2, col = thresh.color[3 : 1], lty = c(4, 2, 1))
hist(p, prob = TRUE, breaks = seq(0, 1, by = 0.01), xlab = "", add = TRUE, col = rgb(0, 0, 0, 0.75))

set.seed(5)
p.norm.1 <- pnorm(-abs(rnorm(1e4))) * 2
set.seed(25)
p.norm.1.6 <- pnorm(-abs(rnorm(1e4, 0, 1.6))) * 2
y.max <- -log(min(p.norm.1, p, p.norm.1.6))
y.max <- 20

par(mar = c(4.5, 4, 4.5, 1)) # make the plots be closer together

plot(sample(-log(p)), ylim = c(0, y.max), ylab = "", main = expression(atop('-log(p-val) of', "Figure 1(c) z-scores")), cex.main = 1.5, cex.lab = 1.5)
title(ylab = '-log(p)', cex.lab = 1.5, line = 2.5)
abline(h = -log(c(
  0.005,
  pnorm(-sqrt(2 * log(1e4))) * 2,
  0.05 / 1e4
)), lwd = 2, col = thresh.color, lty = c(1, 2, 4))

plot(-log(p.norm.1), ylim = c(0, y.max), ylab = "", main = expression(atop('-log(p-val) of', "iid N(0,1) samples")), col = "blue", cex.main = 1.5, cex.lab = 1.5)
title(ylab = '-log(p)', cex.lab = 1.5, line = 2.5)
abline(h = -log(c(
  0.005,
  pnorm(-sqrt(2 * log(1e4))) * 2,
  0.05 / 1e4
)), lwd = 2, col = thresh.color, lty = c(1, 2, 4))

plot(-log(p.norm.1.6), ylim = c(0, y.max), ylab = "", main = expression(atop('-log(p-val) of', paste("iid ", N(0, 1.6^2), " samples"))), col = "green", cex.main = 1.5, cex.lab = 1.5)
title(ylab = '-log(p)', cex.lab = 1.5, line = 2.5)
abline(h = -log(c(
  0.005,
  pnorm(-sqrt(2 * log(1e4))) * 2,
  0.05 / 1e4
)), lwd = 2, col = thresh.color, lty = c(1, 2, 4))

#legend("topright", inset = c(-0.5, 0), legend = c("p = 0.005", "Universal Threshold", "Bonferroni"), lty = 1, lwd = 2, xpd = NA, col = c("red", "orange", "yellow"), ncol = 1, cex = 1.25)

legend("topright", inset = c(-0.82, 0.3),
       legend = c(
         latex2exp::TeX('p-val = $0.05 / 10^4$'),
         'Univ Thresh',
         "p-val = 0.005"
         ), lty = c(4, 2, 1), lwd = 2, xpd = NA,
       col = thresh.color[3 : 1], ncol = 1, cex = 1.25, bty = "n")

dev.off()
```

## Deconv

```{r}
library(ggplot2)

CDF.KW <- function(h, interp = FALSE, eps = 0.001, bw = 0.7){
    #Wasserstein distance:  ||G-H||_W
    if(interp == "biweight"){
	yk = h$x
	for (j in 1:length(yk))
	    yk[j] = sum(biweight(h$x[j], h$x, bw = bw)*h$y/sum(h$y))
	H <- cumsum(yk)
	H <- H/H[length(H)]
    }
    else {
	H <- cumsum(h$y)
	H <- H/H[length(H)]
    }
    return(H)
}
```

```{r}
G <- function (t) {
  0.6 * pnorm(t, 0, 0) + 0.3 * pnorm(t, 0, 1) + 0.1 * pnorm(t, 0, 3)
}

set.seed(777)

theta <- sample(c(
  rnorm(6e3, 0, 0),
  rnorm(3e3, 0, 1),
  rnorm(1e3, 0, 3)
))

x.plot <- seq(-6, 6, by = 0.1)

G.plot <- G(x.plot)
```

```{r}
top_genes_index = function (g, X) {
  return(order(rowSums(X), decreasing = TRUE)[1 : g])
}
lcpm = function (r) {
  R = colSums(r)
  t(log2(((t(r) + 0.5) / (R + 1)) * 10^6))
}
r <- readRDS("../data/liver.rds")
nsamp <- 5
ngene <- 1e4
Y = lcpm(r)
subset = top_genes_index(ngene, Y)
r = r[subset,]
set.seed(777)
counts <- r[, sample(ncol(r), 2 * nsamp)]
design <- model.matrix(~c(rep(0, nsamp), rep(1, nsamp)))
summary <- count_to_summary(counts, design)
s <- summary$sebetahat
s <- s / sqrt(mean(s^2))
```

```{r}
q <- 0.1
p.val.3 <- pnorm(-abs((theta + s * z.sel[3, ]) / s)) * 2
fit.BH.3 <- p.adjust(p.val.3, method = "BH")
sum(fit.BH.3 <= q)
sum(theta[fit.BH.3 <= q] == 0)
sum(theta[fit.BH.3 <= q] == 0) / sum(fit.BH.3 <= q)
fit.qvalue.3 <- qvalue::qvalue(p.val.3)
fit.qvalue.3$pi0
sum(fit.qvalue.3$qvalues <= q)
sum(theta[fit.qvalue.3$qvalues <= q] == 0)
sum(theta[fit.qvalue.3$qvalues <= q] == 0) / sum(fit.qvalue.3$qvalues <= q)
```

```{r, cache = TRUE}
noise.label <- c(
  'a',
  'b',
  'c',
  'd',
  'e'
)
deconv.list <- list()
for (i in 1 : 5) {
  if (i <= 4) {
    Z <- z.sel[i, ]
  } else {
    set.seed(777)
    Z <- rnorm(1e4)
  }
    X <- theta + s * Z
    z <- theta + Z

  ## Truth
  true.data <- cbind.data.frame(
    method = "True g",
    x = x.plot,
    cdfhat = G.plot
  )

  ## ashr
  fit.ashr <- ashr::ash(X, s, method = "fdr", mixcompdist = "normal")
  ashr.plot <- as.numeric(ashr::mixcdf(ashr::get_fitted_g(fit.ashr), x.plot))
  ashr.data <- cbind.data.frame(
    method = "ashr",
    x = x.plot,
    cdfhat = ashr.plot
  )
  
  ## cashr
  fit.cashr <- gdash(X, s)
  cashr.plot <- as.numeric(ashr::mixcdf(ashr::get_fitted_g(fit.cashr), x.plot))
  cashr.data <- cbind.data.frame(
    method = "cashr",
    x = x.plot,
    cdfhat = cashr.plot
  )

  ## deconvolveR
  fit.deconvolveR <- deconvolveR::deconv(tau = x.plot, X = z, family = "Normal", deltaAt = 0)
  deconvolveR.data <- cbind.data.frame(
    method = "deconvolveR",
    x = fit.deconvolveR$stats[, 1],
    cdfhat = fit.deconvolveR$stats[, 4]
  )
  
  ## Kiefer-Wolfowitz's NPMLE (1956)
  ## implemented by Koenker-Mizera-Gu's REBayes (2016)
  v = seq(-6.025, 6.025, by = 0.05)
  fit.REBayes <- REBayes::GLmix(x = X, v = v, sigma = s)
  REBayes.plot <- CDF.KW(fit.REBayes)
  REBayes.data <- cbind.data.frame(
    method = "REBayes",
    x = fit.REBayes$x,
    cdfhat = REBayes.plot
  )
  
  ## EbayesThresh
  fit.EbayesThresh <- EbayesThresh::ebayesthresh(X, sdev = s, verbose = TRUE, prior = "laplace", a = NA)
  EbayesThresh.plot <- (1 - fit.EbayesThresh$w) * (x.plot >= 0) + fit.EbayesThresh$w * rmutil::plaplace(x.plot, m = 0, s = 1 / fit.EbayesThresh$a)
  EbayesThresh.data <- cbind.data.frame(
    method = "EbayesThresh",
    x = x.plot,
    cdfhat = EbayesThresh.plot
  )
  
  deconv.list[[i]] <- cbind.data.frame(
    noise = noise.label[i],
    rbind.data.frame(
      true.data,
      EbayesThresh.data,
      REBayes.data,
      ashr.data,
      deconvolveR.data,
      cashr.data
    )
  )
}
```

```{r}
deconv.ggdata <- do.call(rbind.data.frame, deconv.list)
noise.level <- c("(a)",
                  "(b)",
                  "(c)",
                  "(d)",
                  "(e)")
deconv.ggdata$noise <- plyr::mapvalues(deconv.ggdata$noise,
                                        from = noise.label,
                                        to = noise.level
                                        )
deconv.ggdata$noise <- factor(deconv.ggdata$noise,
                              levels = levels(deconv.ggdata$noise)[c(1, 2, 5, 3, 4)]
                              )
```

```{r}
method.col <- c("black", scales::hue_pal()(5)[c(1, 3, 4, 2, 5)])
method.linetype <- rep(1, 6)
#method.linetype <- c(1, 2, 4, 5, 6)
```

```{r}
## plotting
deconv.plot <- ggplot(data = deconv.ggdata, aes(x = x, y = cdfhat, col = method, linetype = method)) +
  geom_line(size = 1) +
  facet_wrap(~noise, nrow = 2) +
  xlim(-5, 5) +
  scale_linetype_manual(values = method.linetype
                        #, labels = method.name
                        #, guide = guide_legend(nrow = 1)
                        ) +
  scale_color_manual(values = method.col
                     #, labels = method.name
                     #, guide = guide_legend(nrow = 1)
                     ) +
  labs(y = expression(paste("CDF of estimated ", hat(g)))
       #, x = expression(theta)
       #, title = expression(g == 0.6~delta[0] + 0.3~N(0, 1) + 0.1~N(0, 3^2))
       ) +
  theme(plot.title = element_text(size = 15, hjust = 0.5),
        axis.title.x = element_blank(),
        axis.text.x = element_text(size = 10),
        axis.title.y = element_text(size = 15),
        axis.text.y = element_text(size = 10),
        strip.text = element_text(size = 15),
        legend.position = c(0.85, 0.25),
        legend.title = element_blank(),
        #legend.background = element_rect(color = "grey"),
        legend.text = element_text(size = 15))

ggsave("../output/paper/deconv.pdf", height = 5, width = 10)
```
