---
title: "The leukemia figure in `cashr`"
author: "Lei Sun"
date: "2018-10-04"
output:
  workflowr::wflow_html:
    code_folding: hide
---

## Introduction

Document the leukemia figure in the `cashr` paper.

## Load data

```{r, message = FALSE, warning = FALSE}
source("../code/gdash_lik.R")
source("../code/gdfit.R")
```

```{r, cache = TRUE}
load(url("http://statweb.stanford.edu/~ckirby/brad/LSI/datasets-and-programs/data/leukdata.RData"))
```

## Use Smyth's pipeline to obtain summary statistics

```{r}
design <- c(rep(0, 47), rep(1, 25))
lim = limma::lmFit(leukdata, model.matrix(~design))
r.ebayes = limma::eBayes(lim)
p = r.ebayes$p.value[, 2]
t = r.ebayes$t[, 2]
z = -sign(t) * qnorm(p/2)
x = lim$coefficients[, 2]
s = x / z
```

## `locfdr`

```{r}
fit.locfdr <- locfdr::locfdr(z)
```

## `qvalue`

```{r}
fit.qvalue <- qvalue::qvalue(p)
```

## `ashr`

```{r, cache = TRUE}
fit.ash <- ashr::ash(x, s, mixcompdist = "normal", method = "fdr")
lfdr.ash.n <- ashr::get_lfdr(fit.ash)
num.ash.n <- sum(lfdr.ash.n <= 0.2)

pdf("../output/fig/ashr_diag_norm_leukemia.pdf", height = 6, width = 8)
par(mfrow = c(2, 2))
ashr::plot_diagnostic(fit.ash, plot.hist = TRUE, breaks = 50)
dev.off()

fit.ash.u <- ashr::ash(x, s, method = "fdr")
lfdr.ash.u <- ashr::get_lfdr(fit.ash.u)
num.ash.u <- sum(lfdr.ash.u <= 0.2)

pdf("../output/fig/ashr_diag_unif_leukemia.pdf", height = 6, width = 8)
par(mfrow = c(2, 2))
ashr::plot_diagnostic(fit.ash.u, plot.hist = TRUE, breaks = 50)
dev.off()

fit.ash.hu <- ashr::ash(x, s, method = "fdr", mixcompdist = "halfuniform")
lfdr.ash.hu <- ashr::get_lfdr(fit.ash.hu)
num.ash.hu <- sum(lfdr.ash.hu <= 0.2)

xplot <- seq(-2, 2, length = 1000)
plot(xplot, ashr:::dens(get_fitted_g(fit.ash), xplot), type = "l", xlim = c(-1, 1),
     xlab = expression(theta), ylab = expression(pi[1]~g(theta)))
yplot.u <- yplot.hu <- c()
for (i in seq(xplot)) {
  yplot.u[i] <- sum(dunif(xplot[i], get_fitted_g(fit.ash.u)$a[-1], get_fitted_g(fit.ash.u)$b[-1]) * get_fitted_g(fit.ash.u)$pi[-1])
  yplot.hu[i] <- sum(dunif(xplot[i], get_fitted_g(fit.ash.hu)$a[-1], get_fitted_g(fit.ash.hu)$b[-1]) * get_fitted_g(fit.ash.hu)$pi[-1])
}
lines(xplot, yplot.u, col = "blue", lty = 2)
lines(xplot, yplot.hu, col = "red", lty = 3)
legend("topleft", lty = 1:3, col = c("black", "blue", "red"), c("normal", "uniform", "halfuniform"))
```

## `cashr`

```{r}
fit.cash <- gdash(x, s, gd.ord = 10)
```

## Plotting

```{r}
x.plot <- seq(-10, 10, length = 1000)
gd.ord <- 10
hermite = Hermite(gd.ord)
gd0.std = dnorm(x.plot)
matrix_lik_plot = cbind(gd0.std)
for (i in 1 : gd.ord) {
  gd.std = (-1)^i * hermite[[i]](x.plot) * gd0.std / sqrt(factorial(i))
  matrix_lik_plot = cbind(matrix_lik_plot, gd.std)
}
y.plot = matrix_lik_plot %*% fit.cash$w * fit.cash$fitted_g$pi[1]

method.col <- scales::hue_pal()(5)

setEPS()
postscript("../output/paper/leukemia.eps", height = 5, width = 12)
# pdf("../output/paper/leukemia.pdf", height = 5, width = 12)

par(mfrow = c(1, 2))

#####

hist(z, prob = TRUE, main = "", xlab = expression(paste(z, "-scores")), cex.lab = 1.25)

lines(x.plot, y.plot, col = method.col[5], lwd = 2)
lines(x.plot, dnorm(x.plot), col = "orange", lty = 2, lwd = 2)
lines(x.plot, dnorm(x.plot, fit.locfdr$fp0[3, 1], fit.locfdr$fp0[3, 2]) * fit.locfdr$fp0[3, 3], col = method.col[3], lty = 2, lwd = 2)

text(-3.5, 0.188, "N(0,1)", col = "orange")
arrows(-2.2, 0.188, -1.3, 0.183, length = 0.1, angle = 20, col = "orange")

text(-6.5, 0.11, bquote(atop(" locfdr empirical null", .(round(fit.locfdr$fp0[3, 3], 2)) %*% N(.(round(fit.locfdr$fp0[3, 1], 2)), .(round(fit.locfdr$fp0[3, 2], 2))^2))), col = method.col[3])
arrows(-2.8, 0.1115, -1.9, 0.1065, length = 0.1, angle = 20, col = method.col[3])

text(4.8, 0.1025, "cashr null", col = method.col[5])
arrows(2.9, 0.10, 2, 0.095, length = 0.1, angle = 20, col = method.col[5])

####

plot(z, z, type = "n", ylim = c(0, 1), ylab = "Local FDR", xlab = expression(paste(z, "-scores")), cex.lab = 1.25)

points(z, fit.cash$lfdr, pch = 15, cex = 0.5, col = method.col[5])
points(z, fit.locfdr$fdr, pch = 16, cex = 0.5, col = method.col[3])
points(z, fit.qvalue$lfdr, pch = 17, cex = 0.5, col = method.col[2])
points(z, ashr::get_lfdr(fit.ash), pch = 18, cex = 0.5, col = method.col[4])

abline(h = 0.2, lty = 2)

legend("topright", bty = "n", pch = 15 : 18, col = method.col[c(5, 3, 2, 4)], c("cashr", "locfdr", "qvalue", "ashr"))

dev.off()
```
