---
title: "`cashr` comparison: `ashr` with `uniform`: $\\pi_0 = 0.99$"
author: "Lei Sun"
date: "2018-10-11"
output:
  workflowr::wflow_html:
    code_folding: hide
---

## Introduction

Following [previous investigations](cash_plots_4.html), we take a look at

2. What's happening when the median FDP given by `cashr` is better than other methods with $\pi_0 = 0.99$.

```{r packages, message = FALSE, warning = FALSE}
library(ggplot2)
```

```{r functions}
FDP <- function (FDR, qvalue, beta) {
  return(sum(qvalue <= FDR & beta == 0) / max(sum(qvalue <= FDR), 1))
}

TDP <- function (FDR, qvalue, beta) {
  return(sum(qvalue <= FDR & beta != 0) / sum(beta != 0))
}

boxplot.quantile <- function(x) {
  r <- quantile(x, probs = c(0.10, 0.25, 0.5, 0.75, 0.90))
  names(r) <- c("ymin", "lower", "middle", "upper", "ymax")
  return(r)
}

boxplot.quantile.sq <- function (x) {
  r <- sqrt(quantile(x^2, probs = c(0.10, 0.25, 0.5, 0.75, 0.90)))
  names(r) <- c("ymin", "lower", "middle", "upper", "ymax")
  return(r)
}

mean.sq <- function (x) {
  r <- sqrt(mean(x^2))
  return(r)
}

mysqrt_trans <- function() {
  scales::trans_new("mysqrt", 
                    transform = base::sqrt,
                    inverse = function(x) ifelse(x<0, 0, x^2),
                    domain = c(0, Inf))
}
```


```{r}
beta.list <- readRDS("~/Desktop/g/beta.list.nearnormal.rds")
pi0.list <- readRDS("~/Desktop/g/pi0.list.nearnormal.rds")
z.list <- readRDS("~/Desktop/g/z.list.nearnormal.rds")
qvalue.list <- readRDS("~/Desktop/g/qvalue.list.nearnormal.rds")
```

```{r}
q.vec <- 0.1
q <- 0.1
method.name.FDR <- c("cashr", "BH", "qvalue", "ashr", "locfdr")
method.col.FDR <- scales::hue_pal()(length(method.name.FDR))[c(5, 1, 2, 4, 3)]
```

```{r, cache = TRUE}
sd.z <- sapply(z.list, sd)
Noise <- cut(sd.z, breaks = c(0, quantile(sd.z, probs = 1 : 2 / 3), Inf), labels = c("Pseudo Deflation", "In-between", "Pseudo Inflation"))
typical.noise <- order(sd.z)[floor(quantile(seq(sd.z), c(0.1, 0.5, 0.9)))]

##================================================================

FDP.list <- lapply(q.vec, function (q) {
  t(mapply(function(qvalue.mat, beta, q) {
    apply(qvalue.mat, 2, function (qvalue, q, beta) {
      FDP(q, qvalue, beta)
    }, q, beta)
  }, qvalue.list, beta.list, q))
})
names(FDP.list) <- q.vec

TDP.list <- lapply(q.vec, function(q) {
  t(mapply(function(qvalue.mat, beta, q) {
    apply(qvalue.mat, 2, function (qvalue, q, beta) {
      TDP(q, qvalue, beta)
    }, q, beta)
  }, qvalue.list, beta.list, q))
})
names(TDP.list) <- q.vec
```

```{r}
FDP.q <- data.frame(FDP.list[[which(q.vec == q)]])
colnames(FDP.q)[4 : 5] <- c("ashr", "cashr")
FDP.q <- FDP.q[, c(5, 1, 2, 4, 3)]
FDP.q.noise.mat <- rbind.data.frame(
  cbind.data.frame(Noise = rep("All", length(Noise)),
                   pi0 = do.call(rbind, pi0.list),
                   FDP.q),
  cbind.data.frame(Noise,
                   pi0 = do.call(rbind, pi0.list),
                   FDP.q)
)

FDP.q.ggdata <- reshape2::melt(FDP.q.noise.mat, id.vars = c("Noise", "pi0"), variable.name = "Method", value.name = "FDP")
```

## Replicating [the previous results](cash_paper_fig_g1sep.html)

```{r}
FDP.sqrt.q.all.sep.plot <- ggplot(data = FDP.q.ggdata, aes(x = Method, y = FDP, fill = Method, color = Method)) +
  stat_summary(fun.data = boxplot.quantile.sq, geom = "boxplot", aes(width = 0.75), position = position_dodge(), show.legend = FALSE) +
  stat_summary(fun.y = mean.sq, geom = "point", position = position_dodge(width = 0.9), show.legend = FALSE, shape = 13, size = 3) +
  scale_x_discrete(limits = rev(levels(FDP.q.ggdata$Method))) +
  scale_y_continuous(trans = "mysqrt", breaks = c(0, 0.1, 0.2, 0.4, 0.6, 0.8)) +
  coord_flip() +
  scale_color_manual(labels = method.name.FDR, values = method.col.FDR) +
  scale_fill_manual(labels = method.name.FDR, values = alpha(method.col.FDR, 0.35)) +
  facet_grid(pi0 ~ Noise) +
  geom_hline(yintercept = q, col = "black", linetype = "dashed", size = 1) +
  labs(y = "FDP") +
  expand_limits(y = 0) +
  theme(plot.title = element_text(size = 12, hjust = 0),
        axis.title.y = element_blank(),
        axis.text.y = element_text(size = 15),
        axis.title.x = element_text(size = 15),
        axis.text.x = element_text(size = 10),
        strip.text = element_text(size = 15),
        legend.position = "bottom",
        legend.background = element_rect(color = "grey"),
        legend.text = element_text(size = 12)
        )

FDP.sqrt.q.all.sep.plot
```

```{r}
num.d <- lapply(qvalue.list, function (x) {apply(x, 2, function (y) sum(y <= q))})
BH.fdp.0 <- pi0.list == 0.99 & FDP.q$cashr != 0 & FDP.q$BH == 0
temp <- data.frame(t(sapply(num.d[BH.fdp.0], c)))
BH.fdp.0.mat <- cbind.data.frame(
 Noise = Noise[BH.fdp.0],
 BH = temp$BH,
 cashr = temp$CASH,
 cashr.TD = temp$CASH * (1 - FDP.q$cashr[BH.fdp.0]),
 cashr.FD = temp$CASH * FDP.q$cashr[BH.fdp.0],
 cashr.FDP = FDP.q$cashr[BH.fdp.0]
)
plot(BH.fdp.0.mat$BH, BH.fdp.0.mat$cashr.TD, xlab = "Number of True Discoveries by BH", ylab = "Number of True Discoveries by cashr", xlim = c(0, 31), ylim = c(0, 31), col = BH.fdp.0.mat$Noise, type = "n")
abline(0, 1)
text(BH.fdp.0.mat$BH, BH.fdp.0.mat$cashr.TD, labels = BH.fdp.0.mat$cashr.FD, cex = 0.75, col = as.numeric(BH.fdp.0.mat$Noise))
legend("bottomright", col = c("black", "red", "green"), pch = 19, c("Pseudo Deflation", "In-between", "Pseudo Inflation"))

cashr.fdp.0 <- pi0.list == 0.99 & FDP.q$cashr == 0 & FDP.q$BH != 0
temp <- data.frame(t(sapply(num.d[cashr.fdp.0], c)))
cashr.fdp.0.mat <- cbind.data.frame(
 Noise = Noise[cashr.fdp.0],
 BH = temp$BH,
 BH.TD = temp$BH * (1 - FDP.q$BH[cashr.fdp.0]),
 BH.FD = temp$BH * FDP.q$BH[cashr.fdp.0],
 BH.FDP = FDP.q$BH[cashr.fdp.0],
 cashr = temp$CASH
)
plot(cashr.fdp.0.mat$BH.TD, cashr.fdp.0.mat$cashr, xlab = "Number of True Discoveries by BH", ylab = "Number of True Discoveries by cashr", xlim = c(0, 36), ylim = c(0, 36), col = cashr.fdp.0.mat$Noise, type = "n")
abline(0, 1)
text(cashr.fdp.0.mat$BH.TD, cashr.fdp.0.mat$cashr, labels = cashr.fdp.0.mat$BH.FD, cex = 0.75, col = as.numeric(cashr.fdp.0.mat$Noise))
legend("topleft", col = c("black", "red", "green"), pch = 19, c("Pseudo Deflation", "In-between", "Pseudo Inflation"))
```
