---
title: "Empirical Null with Gaussian Derivatives"
author: "Lei Sun"
date: 2017-03-22
output: html_document
---

```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

```{r knitr-opts-chunk, include=FALSE}
```

**Last updated:** `r Sys.Date()`

**Code version:** `r workflowr::extract_commit(".", 1)$sha1`


```{r}
source("../code/ecdfz.R")
```

```{r}
z = read.table("output/z_null_liver_777.txt")
z327 = as.numeric(z[327, ])
w.init = 0
fit.ecdfz = list()
for (ord in 1 : 10) {
  fit.ecdfz[[ord]] = ecdfz(z327, ord, w.init)
  w.init = c(fit.ecdfz[[ord]]$w, 0)
}
fit1 = ecdfz(z327, 1)
fit2 = ecdfz(z327, 2, w.init = c(fit1$w, 0))
f0 = (sapply(1 : 4, EQL::hermite, x = seq(-4.5, 4.5, 0.01)) %*% w$w + 1) * dnorm(seq(-4.5, 4.5, 0.01))
hist(as.numeric(z[724, ]), probability = TRUE, breaks = 100, ylim = c(0, dnorm(0)), xlab = "z scores", main = "Histogram of Data Set 724")
lines(seq(-4.5, 4.5, 0.01), dnorm(seq(-4.5, 4.5, 0.01)), col = "red")
lines(seq(-4.5, 4.5, 0.01), dnorm(seq(-4.5, 4.5, 0.01), mean = mean(as.numeric(z[724, ])), sd = sd(as.numeric(z[724, ]))), col = "green")
lines(seq(-4.5, 4.5, 0.01), f0, col = "blue")
legend("topright", lty = 1, col = c("red", "green", "blue"), c("N(0, 1)", expression(N(hat(mu),hat(sigma)^2)), "Gaussian Derivatives"))
```

## Session Information

```{r session-info}
```
